/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. This does not assert database/provider readiness.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Trip
         * @description Validate a draft without saving it or asserting itinerary feasibility.
         */
        post: operations["validateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["listTrips"];
        put?: never;
        /** Create Trip */
        post: operations["createTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["getTrip"];
        /** Update Trip */
        put: operations["updateTrip"];
        post?: never;
        /** Delete Trip */
        delete: operations["deleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["getProfile"];
        /** Save Profile */
        put: operations["saveProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/{trip_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["getRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Anchor */
        Anchor: {
            /** Label */
            label: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][];
        };
        /** Budget */
        Budget: {
            /** Amount Vnd */
            amount_vnd: number;
            /**
             * Scope
             * @default per_person
             * @enum {string}
             */
            scope: "per_person" | "group";
            /**
             * Mode
             * @default soft
             * @enum {string}
             */
            mode: "soft" | "hard";
            /**
             * Currency
             * @default VND
             * @constant
             */
            currency: "VND";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** Evidence */
        Evidence: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            /** Fields */
            fields: ("identity" | "coordinates" | "tags" | "access" | "price" | "hours" | "duration")[];
            /** Note */
            note: string;
        };
        /** FixedEvent */
        FixedEvent: {
            /** Label */
            label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default wayo-api
             * @constant
             */
            service: "wayo-api";
            /**
             * Version
             * @default 0.1.0
             * @constant
             */
            version: "0.1.0";
        };
        /** InputNotice */
        InputNotice: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** OpeningWindow */
        OpeningWindow: {
            /**
             * Weekday
             * @description Monday=0; Vietnam local time
             */
            weekday: number;
            /** Opens */
            opens: string;
            /** Closes */
            closes: string;
        };
        /**
         * Pace
         * @enum {string}
         */
        Pace: "relaxed" | "balanced" | "active";
        /** PlaceRecord */
        PlaceRecord: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Slug */
            slug: string;
            /**
             * Destination Id
             * @default da-lat
             * @constant
             */
            destination_id: "da-lat";
            /** Name */
            name: string;
            /** Address */
            address: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cafe" | "food" | "nature" | "attraction" | "nightlife" | "culture";
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Tags */
            tags: ("cafe" | "nature" | "photography" | "food" | "culture" | "nightlife")[];
            /**
             * Status
             * @default draft
             * @enum {string}
             */
            status: "draft" | "verified" | "stale" | "disabled";
            /** Trekking */
            trekking?: boolean | null;
            /** Stairs */
            stairs?: boolean | null;
            /** Alcohol */
            alcohol?: boolean | null;
            /** Crowd */
            crowd?: ("quiet" | "moderate" | "busy") | null;
            price?: components["schemas"]["Price"] | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Hours */
            hours?: components["schemas"]["OpeningWindow"][] | null;
            /** Sources */
            sources: components["schemas"]["Evidence"][];
        };
        /** Price */
        Price: {
            /** Min Vnd */
            min_vnd: number;
            /** Max Vnd */
            max_vnd: number;
            /**
             * Unit
             * @enum {string}
             */
            unit: "per_person" | "group";
        };
        /** ProfileUpdate */
        ProfileUpdate: {
            /** Expected Revision */
            expected_revision: number;
            answers: components["schemas"]["TasteAnswers"];
        };
        /** Recommendations */
        Recommendations: {
            /** Trip Revision */
            trip_revision: number;
            /**
             * Algorithm Version
             * @default saved-trip-tags-v1
             */
            algorithm_version: string;
            /** Items */
            items: components["schemas"]["SuggestedPlace"][];
            /** Notices */
            notices: components["schemas"]["InputNotice"][];
        };
        /** SavedProfile */
        SavedProfile: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            answers?: components["schemas"]["TasteAnswers"] | null;
            /** Vector */
            vector?: {
                [key: string]: number;
            };
            /** Updated At */
            updated_at?: string | null;
        };
        /** SavedTrip */
        SavedTrip: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            trip: components["schemas"]["TripRequest"];
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SuggestedPlace */
        SuggestedPlace: {
            place: components["schemas"]["PlaceRecord"];
            /** Matched Interests */
            matched_interests: string[];
            /** Reasons */
            reasons: string[];
            /** Warnings */
            warnings: string[];
        };
        /** TasteAnswers */
        TasteAnswers: {
            /** Interests */
            interests: ("cafe" | "nature" | "photography" | "food" | "culture" | "nightlife")[];
            /**
             * Pace
             * @enum {string}
             */
            pace: "relaxed" | "balanced" | "active";
            /**
             * Crowd
             * @enum {string}
             */
            crowd: "quiet" | "neutral" | "lively";
            /**
             * Adventure
             * @enum {string}
             */
            adventure: "easy" | "moderate" | "challenging";
            /**
             * Diet
             * @enum {string}
             */
            diet: "unrestricted" | "vegetarian" | "vegan";
            /** Exclusions */
            exclusions: ("trekking" | "stairs" | "alcohol")[];
        };
        /** TripCreate */
        TripCreate: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Title */
            title: string;
            trip: components["schemas"]["TripRequest"];
        };
        /** TripList */
        TripList: {
            /** Items */
            items: components["schemas"]["SavedTrip"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /** TripRequest */
        TripRequest: {
            /**
             * Destination Id
             * @default da-lat
             * @constant
             */
            destination_id: "da-lat";
            /** Origin */
            origin: string;
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            /**
             * Timezone
             * @default Asia/Ho_Chi_Minh
             * @constant
             */
            timezone: "Asia/Ho_Chi_Minh";
            /** People Count */
            people_count: number;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "couple" | "friends";
            budget: components["schemas"]["Budget"];
            /**
             * Transport Mode
             * @default driving
             * @constant
             */
            transport_mode: "driving";
            /** @default relaxed */
            pace: components["schemas"]["Pace"];
            anchor?: components["schemas"]["Anchor"] | null;
            /** Preferences */
            preferences?: string[];
            /** Exclusions */
            exclusions?: string[];
            /** Fixed Events */
            fixed_events?: components["schemas"]["FixedEvent"][];
        };
        /** TripUpdate */
        TripUpdate: {
            /** Expected Revision */
            expected_revision: number;
            /** Title */
            title: string;
            trip: components["schemas"]["TripRequest"];
        };
        /** TripValidation */
        TripValidation: {
            /**
             * Status
             * @default input_valid
             * @constant
             */
            status: "input_valid";
            /** Trip Days */
            trip_days: number;
            /** Total Budget Vnd */
            total_budget_vnd: number;
            /** Notices */
            notices: components["schemas"]["InputNotice"][];
            trip: components["schemas"]["TripRequest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    validateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripValidation"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listTrips: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Previously created request replay */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTrip"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTrip"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTrip"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedTrip"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteTrip: {
        parameters: {
            query: {
                expected_revision: number;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    saveProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRecommendations: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendations"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
