/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. This does not assert database/provider readiness.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/trips/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Trip
         * @description Validate a draft without saving it or asserting itinerary feasibility.
         */
        post: operations["validateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Anchor */
        Anchor: {
            /** Label */
            label: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][];
        };
        /** Budget */
        Budget: {
            /** Amount Vnd */
            amount_vnd: number;
            /**
             * Scope
             * @default per_person
             * @enum {string}
             */
            scope: "per_person" | "group";
            /**
             * Mode
             * @default soft
             * @enum {string}
             */
            mode: "soft" | "hard";
            /**
             * Currency
             * @default VND
             * @constant
             */
            currency: "VND";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** FixedEvent */
        FixedEvent: {
            /** Label */
            label: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @default wayo-api
             * @constant
             */
            service: "wayo-api";
            /**
             * Version
             * @default 0.1.0
             * @constant
             */
            version: "0.1.0";
        };
        /** InputNotice */
        InputNotice: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * Pace
         * @enum {string}
         */
        Pace: "relaxed" | "balanced" | "active";
        /** TripRequest */
        TripRequest: {
            /**
             * Destination Id
             * @default da-lat
             * @constant
             */
            destination_id: "da-lat";
            /** Origin */
            origin: string;
            /**
             * Arrival At
             * Format: date-time
             */
            arrival_at: string;
            /**
             * Departure At
             * Format: date-time
             */
            departure_at: string;
            /**
             * Timezone
             * @default Asia/Ho_Chi_Minh
             * @constant
             */
            timezone: "Asia/Ho_Chi_Minh";
            /** People Count */
            people_count: number;
            /**
             * Group Type
             * @enum {string}
             */
            group_type: "couple" | "friends";
            budget: components["schemas"]["Budget"];
            /**
             * Transport Mode
             * @default driving
             * @constant
             */
            transport_mode: "driving";
            /** @default relaxed */
            pace: components["schemas"]["Pace"];
            anchor?: components["schemas"]["Anchor"] | null;
            /** Preferences */
            preferences?: string[];
            /** Exclusions */
            exclusions?: string[];
            /** Fixed Events */
            fixed_events?: components["schemas"]["FixedEvent"][];
        };
        /** TripValidation */
        TripValidation: {
            /**
             * Status
             * @default input_valid
             * @constant
             */
            status: "input_valid";
            /** Trip Days */
            trip_days: number;
            /** Total Budget Vnd */
            total_budget_vnd: number;
            /** Notices */
            notices: components["schemas"]["InputNotice"][];
            trip: components["schemas"]["TripRequest"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    validateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripValidation"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
